# Generated by Django 5.0.1 on 2025-10-22 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('accreditation', models.JSONField(blank=True, default=list, help_text='List of accreditations (NAAC, NBA, etc.)')),
                ('type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('deemed', 'Deemed University'), ('autonomous', 'Autonomous')], max_length=50)),
                ('fees_annual', models.IntegerField(help_text='Annual tuition fees in INR', validators=[django.core.validators.MinValueValidator(0)])),
                ('fees_hostel', models.IntegerField(blank=True, help_text='Annual hostel fees in INR', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('restart_score', models.SmallIntegerField(default=0, help_text='REstart proprietary score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ratings_count', models.IntegerField(default=0)),
                ('reviews_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'college',
                'verbose_name_plural': 'colleges',
                'db_table': 'colleges',
                'ordering': ['-restart_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('degree_type', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20)),
                ('duration_years', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'degree',
                'verbose_name_plural': 'degrees',
                'db_table': 'degrees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_rank', models.IntegerField(blank=True, help_text='Previous year cutoff rank', null=True)),
                ('cutoff_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
            options={
                'verbose_name': 'college exam',
                'verbose_name_plural': 'college exams',
                'db_table': 'college_exams',
                'unique_together': {('college', 'exam')},
            },
        ),
        migrations.AddField(
            model_name='college',
            name='exams_required',
            field=models.ManyToManyField(related_name='colleges', through='colleges.CollegeExam', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='CollegeDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_available', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='colleges.college')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.degree')),
            ],
            options={
                'verbose_name': 'college degree',
                'verbose_name_plural': 'college degrees',
                'db_table': 'college_degrees',
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admission_start', 'Admission Start'), ('admission_end', 'Admission End'), ('counseling', 'Counseling Date'), ('orientation', 'Orientation'), ('semester_start', 'Semester Start')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='colleges.college')),
            ],
            options={
                'verbose_name': 'important date',
                'verbose_name_plural': 'important dates',
                'db_table': 'important_dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criteria', models.TextField(help_text='Eligibility criteria for the scholarship')),
                ('amount', models.IntegerField(blank=True, help_text='Scholarship amount in INR', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='colleges.college')),
            ],
            options={
                'verbose_name': 'scholarship',
                'verbose_name_plural': 'scholarships',
                'db_table': 'scholarships',
            },
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['state', 'city'], name='colleges_state_bcee5e_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['type'], name='colleges_type_0bf8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['restart_score'], name='colleges_restart_5a43f8_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['status'], name='colleges_status_e33a19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collegedegree',
            unique_together={('college', 'degree')},
        ),
    ]
