# Generated by Django 5.0.1 on 2025-10-22 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique exam code (e.g., JEE, NEET)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('pattern', models.TextField(blank=True, help_text='Exam pattern details')),
                ('syllabus_summary', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True, max_length=500)),
                ('dates', models.JSONField(blank=True, default=dict, help_text='Important dates in JSON format')),
                ('cutoffs', models.JSONField(blank=True, default=dict, help_text='Previous year cutoffs in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'db_table': 'exams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration_start', 'Registration Start'), ('registration_end', 'Registration End'), ('exam_date', 'Exam Date'), ('result_date', 'Result Date'), ('counseling_start', 'Counseling Start'), ('counseling_end', 'Counseling End')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_dates', to='exams.exam')),
            ],
            options={
                'verbose_name': 'exam date',
                'verbose_name_plural': 'exam dates',
                'db_table': 'exam_dates',
                'ordering': ['date'],
            },
        ),
    ]
