# Generated by Django 5.0.1 on 2025-10-22 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the week')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated time to complete (hours)', max_digits=4, null=True)),
                ('resources', models.JSONField(blank=True, default=list, help_text='List of resource URLs or references')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'preparation task',
                'verbose_name_plural': 'preparation tasks',
                'db_table': 'prep_tasks',
                'ordering': ['prep_week', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrepWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Week number in the plan (1-indexed)')),
                ('title', models.CharField(blank=True, help_text='Week title/theme', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'preparation week',
                'verbose_name_plural': 'preparation weeks',
                'db_table': 'prep_weeks',
                'ordering': ['prep_plan', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='PrepPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('target_date', models.DateField(blank=True, help_text='Target exam date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_plans', to='exams.exam')),
            ],
            options={
                'verbose_name': 'preparation plan',
                'verbose_name_plural': 'preparation plans',
                'db_table': 'prep_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
