# Generated by Django 5.0.1 on 2025-10-22 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guidance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prepplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prepweek',
            name='prep_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='guidance.prepplan'),
        ),
        migrations.AddField(
            model_name='preptask',
            name='prep_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='guidance.prepweek'),
        ),
        migrations.AlterUniqueTogether(
            name='prepplan',
            unique_together={('user', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='prepweek',
            unique_together={('prep_plan', 'week_number')},
        ),
    ]
