# Generated by Django 5.0.1 on 2025-10-22 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Detailed review text')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Review tags (e.g., 'infrastructure', 'faculty', 'placements')")),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True, help_text='Admin notes for moderation')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this college')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shortlist',
                'verbose_name_plural': 'shortlists',
                'db_table': 'shortlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exam', 'Exam Reminder'), ('college_date', 'College Important Date'), ('exam_date', 'Exam Date')], max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the target object')),
                ('channels', models.JSONField(default=list, help_text='List of notification channels (email, sms, push)')),
                ('days_before', models.PositiveSmallIntegerField(default=7, help_text='Send reminder X days before the date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(help_text='Type of object (Exam, College, ImportantDate, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'reminder subscription',
                'verbose_name_plural': 'reminder subscriptions',
                'db_table': 'reminder_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
