# Generated by Django 5.0.1 on 2025-10-22 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_colleges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='remindersubscription',
            index=models.Index(fields=['content_type', 'object_id'], name='reminder_su_content_e422b3_idx'),
        ),
        migrations.AddIndex(
            model_name='remindersubscription',
            index=models.Index(fields=['is_active'], name='reminder_su_is_acti_0fb0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='reviews_status_12ddaa_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['college', 'status'], name='reviews_college_c142bd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_created_6c5dce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='shortlist',
            unique_together={('user', 'college')},
        ),
    ]
